/* AstroEdu advanced tools. Original educational diagrams; Astronomy Engine ephemerides. */
(function(root){
'use strict';
const D=Math.PI/180;
function orientation(alpha,beta,gamma,screenAngle=0){
 const a=alpha*D,b=beta*D,g=gamma*D,ca=Math.cos(a),sa=Math.sin(a),cb=Math.cos(b),sb=Math.sin(b),cg=Math.cos(g),sg=Math.sin(g);
 const forward=[-ca*sg-sa*sb*cg,-sa*sg+ca*sb*cg,-cb*cg];
 const t=screenAngle*D,x=Math.sin(t),y=Math.cos(t);
 const up=[(ca*cg-sa*sb*sg)*x-sa*cb*y,(sa*cg+ca*sb*sg)*x+ca*cb*y,cb*sg*x+sb*y];
 const az=Math.atan2(forward[0],forward[1]),alt=Math.asin(Math.max(-1,Math.min(1,forward[2])));
 const right=[Math.cos(az),-Math.sin(az),0],vertical=[-Math.sin(alt)*Math.sin(az),-Math.sin(alt)*Math.cos(az),Math.cos(alt)];
 const dot=(u,v)=>u.reduce((s,n,i)=>s+n*v[i],0);
 return {az:(az/D+360)%360,alt:alt/D,roll:Math.atan2(dot(up,right),dot(up,vertical))/D};
}
root.AstroOrientation=orientation;
root.SkyAdvanced=function(H){
 const {state,A,C,canvas,pos,objects,modal,close,toast,fmt,esc,setTime,select,snapshot,download,change}=H,$=s=>document.querySelector(s);
 let panorama=null,stream=null,sensing=false,offset=0,lastOrientation=null,session=0,sensorTimer=null,lastSensor=0;
 let lastSensorPaint=0,calibrated=false,absoluteUntil=0,sensorMessage='方向尚未啟用';
 let lab='system',base=null,answer='',prediction='',orbitYaw=.6,orbitPitch=.55;
 const units={system:['日地月 3D 聯動','月球亮面為何改變？','比較新月與滿月時日地月的位置。','一般月相來自觀測方向，並非地球遮住陽光。'],compare:['雙視窗比較','相隔兩小時，星星在哪裡？','左右固定相同視角，右側為兩小時後。','地球自轉改變恆星的地平位置。'],solar:['日食','每逢新月都會日食嗎？','搜尋下一次當地日食，再查看接觸與食甚時間。','月球軌道傾斜，通常影子不會落在地球上。'],lunar:['月食','每逢滿月都會月食嗎？','搜尋下一次月食，檢查月球高度與食的種類。','滿月還需接近軌道交點才會進入地球影子。'],retro:['行星逆行','火星是否真的倒著繞太陽？','逐日檢查火星赤經軌跡與地球、火星的位置。','地球超越外行星時，視線方向可以暫時向西移動。'],latitude:['緯度與北極星','北極星高度會等於緯度嗎？','改變緯度，比較北極星高度與北天極。','北極星靠近北天極，但不完全重合；南半球通常在地平線下。'],sunpath:['季節太陽路徑','夏至的太陽在各地都最高嗎？','比較二分二至整天路徑，再改變緯度。','日行軌跡由地軸傾角與緯度決定，南北半球季節相反。']};
 const ob=()=>new A.Observer(state.place.lat,state.place.lon,0);
 function horizontal(id,time=state.time){const o=objects.get(id);if(o?.body){const e=A.Equator(id,new Date(time),ob(),true,true),h=A.Horizon(new Date(time),ob(),e.ra,e.dec);return {az:h.azimuth,alt:h.altitude};}const v=A.RotateVector(A.Rotation_EQJ_HOR(new Date(time),ob()),new A.Vector(...o.vec,new Date(time))),h=A.HorizonFromVector(v);return {az:h.lon,alt:h.lat};}
 function riseSet(){const o=objects.get(state.selected);let body=o.id;if(!o.body){A.DefineStar('Star1',C.wrap(o.ra)/15,o.dec,1000);body='Star1';}const start=new Date(state.time),rise=A.SearchRiseSet(body,ob(),1,start,2),set=A.SearchRiseSet(body,ob(),-1,start,2);return `未來 48 小時（標準折射、平坦地平線）\n升起：${rise?fmt(rise.date.getTime()):'此期間無升起事件'}\n落下：${set?fmt(set.date.getTime()):'此期間無落下事件'}\n照片中的山脈遮擋未計入升落時間。`;}
 function open(){modal('進階觀測與教學實驗室',`<p>從真實星圖進入可操作的模型。所有時間均為 UTC+8。</p><div class="advanced-grid">${Object.entries(units).map(([id,u])=>`<button class="course-option" data-advanced="unit" data-unit="${id}">${u[0]} →</button>`).join('')}</div><h3>觀測工具</h3><button class="secondary" data-advanced="rise">${esc(objects.get(state.selected).name)} · 升落時間</button> <button class="secondary" data-advanced="landscape">匯入現場地景</button> <button class="primary" data-advanced="ar">手機指向與相機 AR</button><p class="muted">星座插畫目前提供天鵝、天鷹、天琴、獵戶四個原創教學線描；其餘星座有連線與邊界。</p>`);}
 function labOpen(id){stop();lab=id;base=snapshot();prediction='';answer='';renderLab();}
 function renderLab(){const u=units[lab];modal(u[0],`<p>${u[1]}</p><label>1 · 先預測<input id="lab-prediction" maxlength="1000" placeholder="寫下你的預測" value="${esc(prediction)}"></label><p>2 · 操作觀察：${u[2]}</p><div class="lab-controls"><button data-advanced="step" data-days="-0.0104166667" class="secondary">−15 分</button><button data-advanced="step" data-days="0.0104166667" class="secondary">+15 分</button><button data-advanced="step" data-days="-1" class="secondary">−1 天</button><button data-advanced="step" data-days="1" class="secondary">+1 天</button><button data-advanced="step" data-days="7" class="secondary">+7 天</button><button data-advanced="preset" class="secondary">載入典型情境</button><button data-advanced="lab-reset" class="secondary">重設實驗</button><label>緯度 <input id="lab-lat" type="range" min="-90" max="90" step="1" value="${state.place.lat}"></label>${lab==='solar'||lab==='lunar'?'<button data-advanced="eclipse" class="primary">搜尋下一次事件</button>':''}</div><p id="lab-time"></p><div class="lab-views"><canvas id="lab-model" width="720" height="440" aria-label="可拖曳旋轉的三維教學模型"></canvas><canvas id="lab-plot" width="720" height="440" aria-label="觀測比較圖"></canvas></div><p id="lab-values" class="hint-text"></p><p id="event-details"></p><p class="muted">模型以真實天體方向建立三維投影，球體顏色僅供辨識，月相數據以地球觀點計算；天體尺寸與地月距離放大，不可用圖上大小推算日月食。拖曳左圖可旋轉。右圖為觀測資料。</p><label>3 · 解釋與紀錄<textarea id="lab-answer" maxlength="4000" placeholder="預測符合嗎？請用觀測數據解釋。">${esc(answer)}</textarea></label><details><summary>4 · 對照科學解釋</summary><p>${u[3]}</p></details><button data-advanced="lab-save" class="primary">匯出本次實驗紀錄</button>`);
 $('#lab-prediction').addEventListener('input',e=>prediction=e.target.value);$('#lab-answer').addEventListener('input',e=>answer=e.target.value);
 $('#lab-lat').addEventListener('input',e=>{state.place={...state.place,name:'實驗緯度',lat:Number(e.target.value)};change();paintLab();});
 const cv=$('#lab-model');let pt=null;cv.addEventListener('pointerdown',e=>{pt=[e.clientX,e.clientY];cv.setPointerCapture?.(e.pointerId);});cv.addEventListener('pointermove',e=>{if(!pt)return;orbitYaw+=(e.clientX-pt[0])*.01;orbitPitch=C.clamp(orbitPitch+(e.clientY-pt[1])*.01,-1.4,1.4);pt=[e.clientX,e.clientY];paintLab();});for(const event of ['pointerup','pointercancel'])cv.addEventListener(event,()=>pt=null);paintLab();}
 function chart(ctx,title){ctx.fillStyle='#081426';ctx.fillRect(0,0,720,440);ctx.font='18px "Microsoft JhengHei", system-ui';ctx.fillStyle='#dfeefc';ctx.fillText(title,22,30);}
 function line(ctx,pts,color){ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();let prev=null;for(const p of pts){if(prev&&(pts.length===2||Math.hypot(p[0]-prev[0],p[1]-prev[1])<350))ctx.lineTo(...p);else ctx.moveTo(...p);prev=p;}ctx.stroke();}
 function paintLab(){if(!$('#lab-model'))return;const t=new Date(state.time),g=$('#lab-model').getContext('2d'),p=$('#lab-plot').getContext('2d');chart(g,'三維視角 · 拖曳旋轉');chart(p,units[lab][0]+' · 觀測資料');$('#lab-time').textContent=fmt(state.time)+' · 緯度 '+state.place.lat.toFixed(1)+'°';
 const earth=A.HelioVector('Earth',t),moon=A.GeoMoon(t),sun=A.GeoVector('Sun',t,true),norm=v=>{const n=Math.hypot(v.x,v.y,v.z);return [v.x/n,v.y/n,v.z/n];};
 const project=v=>{const x=v[0]*Math.cos(orbitYaw)-v[1]*Math.sin(orbitYaw),y=v[0]*Math.sin(orbitYaw)+v[1]*Math.cos(orbitYaw),z=y*Math.sin(orbitPitch)+v[2]*Math.cos(orbitPitch),k=520/(520+z);return [360+x*k,230+(y*Math.cos(orbitPitch)-v[2]*Math.sin(orbitPitch))*k,z];};
 const balls=lab==='retro'?[{v:[0,0,0],r:23,c:'#ffcb6b',name:'太陽'},{v:[earth.x*110,earth.y*110,earth.z*110],r:12,c:'#5aaaff',name:'地球'},...['Mars'].map(id=>{const v=A.HelioVector(id,t);return {v:[v.x*110,v.y*110,v.z*110],r:10,c:'#ed9c79',name:'火星'};})]:[{v:[0,0,0],r:28,c:'#58a9e8',name:'地球'},{v:norm(moon).map(x=>x*120),r:12,c:'#d6dce6',name:'月球'},{v:norm(sun).map(x=>x*260),r:25,c:'#ffcb6b',name:'太陽'}];
 const orbit=Array.from({length:181},(_,i)=>{const v=A.GeoMoon(new Date(state.time+(i/180*27.3)*86400000));return project(norm(v).map(x=>x*120));});line(g,orbit,'#47556b');for(const b of balls)line(g,[project([0,0,0]),project(b.v)],'#617887');balls.sort((a,b)=>project(b.v)[2]-project(a.v)[2]);for(const b of balls){const q=project(b.v);const sphere=g.createRadialGradient(q[0]-b.r*.35,q[1]-b.r*.35,1,q[0],q[1],b.r);sphere.addColorStop(0,b.c);sphere.addColorStop(.65,b.c);sphere.addColorStop(1,'#23344c');g.fillStyle=sphere;g.beginPath();g.arc(q[0],q[1],b.r,0,Math.PI*2);g.fill();g.fillStyle='#e9f4ff';g.fillText(b.name,q[0]+b.r+7,q[1]);}
 let values='';if($('#event-details'))$('#event-details').textContent='';
 if(lab==='solar'||lab==='lunar'){
 const eqS=A.Equator('Sun',t,ob(),true,true),eqM=A.Equator('Moon',t,ob(),true,true),sunRadius=Math.asin(695700/(eqS.dist*A.KM_PER_AU))/D,moonRadius=Math.asin(1737.4/(eqM.dist*A.KM_PER_AU))/D;
 let dx,dy,shadeRadius;
 if(lab==='solar'){dx=((eqM.ra-eqS.ra)*15+540)%360-180;dx*=Math.cos(eqS.dec*D);dy=eqM.dec-eqS.dec;shadeRadius=moonRadius;}
 else {const sv=A.GeoVector('Sun',t,true),mv=A.GeoMoon(t),se=A.EquatorFromVector(sv),me=A.EquatorFromVector(mv);const shadowRA=C.wrap(se.ra*15+180),shadowDec=-se.dec;dx=((shadowRA-me.ra*15+540)%360)-180;dx*=Math.cos(me.dec*D);dy=shadowDec-me.dec;shadeRadius=(6378.137/Math.hypot(mv.x,mv.y,mv.z)-(695700-6378.137)/Math.hypot(sv.x,sv.y,sv.z))/A.KM_PER_AU/D;}
 const scale=230,centerRadius=lab==='solar'?sunRadius:moonRadius;
 p.fillStyle=lab==='solar'?'#ffd178':'#d5dfeb';p.beginPath();p.arc(360,225,centerRadius*scale,0,2*Math.PI);p.fill();p.fillStyle=lab==='solar'?'#142036':'#a94c4077';p.beginPath();p.arc(360+dx*scale,225-dy*scale,Math.max(0,shadeRadius)*scale,0,2*Math.PI);p.fill();
 values=`角尺度圖：每 230 像素代表 1°；東在右、北在上。${lab==='solar'?'當地太陽與月球圓盤':'地心月球與地球本影'}中心距離約 ${Math.hypot(dx,dy).toFixed(3)}°。搜尋食甚後以 ±15 分查看遮掩；事件時刻由引擎計算，圖形為小角近似${lab==='lunar'?'，本影未加大氣修正':''}。`;
 }
 else if(lab==='sunpath'){for(const [month,day,color,label] of [[3,20,'#80d7ac','春分'],[6,21,'#ffd178','夏至'],[9,23,'#b3a4ff','秋分'],[12,21,'#87bbef','冬至']]){const season=A.Seasons(t.getUTCFullYear()),st=season[{3:'mar_equinox',6:'jun_solstice',9:'sep_equinox',12:'dec_solstice'}[month]].date;const start=Date.UTC(st.getUTCFullYear(),st.getUTCMonth(),st.getUTCDate())-28800000;const pts=Array.from({length:145},(_,i)=>horizontal('Sun',start+i*600000));line(p,pts.map(v=>[40+v.az/360*640,390-(v.alt+90)/180*330]),color);p.fillStyle=color;p.fillText(label,50+(month/3-1)*155,60);}p.font='12px \"Microsoft JhengHei\", system-ui';p.fillStyle='#a7bdcf';for(let a=0;a<=360;a+=90)p.fillText(a+'°',40+a/360*640,415);for(let a=-90;a<=90;a+=45)p.fillText(a+'°',3,390-(a+90)/180*330);values='橫軸方位 0–360°，縱軸高度 −90–90°。水平中線為地平線。';line(p,[[40,225],[680,225]],'#b2c5d0');}
 else if(lab==='retro'){const times=Array.from({length:181},(_,i)=>state.time+(i-90)*86400000),ras=times.map(t=>A.Equator('Mars',new Date(t),ob(),false,true).ra*15);for(let i=1;i<ras.length;i++){while(ras[i]-ras[i-1]>180)ras[i]-=360;while(ras[i]-ras[i-1]<-180)ras[i]+=360;}const lo=Math.min(...ras),hi=Math.max(...ras);line(p,ras.map((r,i)=>[40+i/180*640,380-(r-lo)/(hi-lo||1)*300]),'#ffb78d');line(p,[[360,70],[360,390]],'#a8cfe5');p.fillStyle='#a7bdcf';p.font='13px \"Microsoft JhengHei\", system-ui';p.fillText(lo.toFixed(1)+'°',5,385);p.fillText(hi.toFixed(1)+'°',5,80);p.fillText('−90 天',40,415);p.fillText('目前',345,415);p.fillText('+90 天',630,415);const delta=ras[91]-ras[90];values=`火星 J2000 赤經，橫軸目前前後 90 天，曲線向下為向西逆行。當日赤經變化 ${delta.toFixed(3)}°／天：${delta<0?'逆行':'順行'}。`;}
 else if(lab==='latitude'){const h=horizontal('11767');line(p,[[-90, -90],[90,90]].map(([x,y])=>[360+x*3.4,220-y*1.8]),'#72bad5');for(let lat=-90;lat<=90;lat+=30){p.fillStyle='#acbdca';p.fillText(lat+'°',360+lat*3.4,420);}p.fillStyle='#ffce82';p.beginPath();p.arc(360+state.place.lat*3.4,220-h.alt*1.8,7,0,Math.PI*2);p.fill();values=`北極星高度 ${h.alt.toFixed(2)}°；北天極高度 ${state.place.lat.toFixed(2)}°。橫軸緯度，縱軸高度（−90 至 90°）。${h.alt<0?'北極星在地平線下。':''}`;}
 else {const id=lab==='compare'?state.selected:'Moon',later=lab==='compare'?state.time+7200000:state.time+7*86400000;for(const [time,x,label] of [[state.time,180,'目前'],[later,540,lab==='compare'?'+2 小時':'+7 天']]){p.strokeStyle='#59738a';p.strokeRect(x-155,70,310,300);for(const o of objects.values()){if(o.dso||o.body||o.mag>3)continue;const h=horizontal(o.id,time),q=C.project(C.altAzVector(h.az,h.alt),state.camera,300,270);if(q&&q.x>0&&q.x<300&&q.y>0&&q.y<270){p.fillStyle='#a7cbe1';p.fillRect(x-150+q.x,90+q.y,2,2);}}const h=horizontal(id,time),q=C.project(C.altAzVector(h.az,h.alt),state.camera,300,270);if(q&&q.x>0&&q.x<300&&q.y>0&&q.y<270){p.fillStyle='#ffcb79';p.beginPath();p.arc(x-150+q.x,90+q.y,6,0,Math.PI*2);p.fill();}p.fillStyle='#dcefff';p.fillText(label,x-140,60);p.font='14px "Microsoft JhengHei", system-ui';p.fillText('高度 '+h.alt.toFixed(1)+'° · 方位 '+h.az.toFixed(1)+'°',x-145,398);}values=`相同視角的兩個觀測視窗。目標 ${objects.get(id).name}，月相 ${C.phaseName(A.MoonPhase(t))}，月球照明 ${((1-Math.cos(A.MoonPhase(t)*D))*50).toFixed(1)}%。目標可能在畫面外或地平線下。`;}
 $('#lab-values').textContent=values;
 }
 function eclipse(){try{let info,peak,details;if(lab==='solar'){info=A.SearchLocalSolarEclipse(new Date(state.time),ob());peak=info.peak.time.date;details=`當地日食 ${info.kind}，遮蔽比例 ${(info.obscuration*100).toFixed(1)}%；初虧 ${fmt(info.partial_begin.time.date.getTime())}；食甚 ${fmt(peak.getTime())}（太陽高度 ${info.peak.altitude.toFixed(1)}°）；復圓 ${fmt(info.partial_end.time.date.getTime())}。${info.total_begin?'全食／環食開始 '+fmt(info.total_begin.time.date.getTime())+'；結束 '+fmt(info.total_end.time.date.getTime()):''} 使用合格太陽濾鏡，勿直視太陽。`;}else{info=A.SearchLunarEclipse(new Date(state.time));peak=info.peak.date;details=`全球月食 ${info.kind}；食甚 ${fmt(peak.getTime())}；半影期 ${Math.round(info.sd_penum*2)} 分鐘，本影部分期 ${Math.round(info.sd_partial*2)} 分鐘，全食期 ${Math.round(info.sd_total*2)} 分鐘。當地食甚月球高度 ${horizontal('Moon',peak.getTime()).alt.toFixed(1)}°；低於地平線表示當時不可見。`;}
 if(peak.getUTCFullYear()>2050){toast('下一事件超出此版 2000–2050 範圍');return;}setTime(peak.getTime());paintLab();$('#event-details').textContent=details;}catch(e){toast('事件搜尋失敗：'+String(e));}}
 function landscape(){modal('匯入現場地景',`<p>選擇自己拍攝、有使用權的 2:1 等距柱狀全景照片。照片中線應為地平線，左邊緣朝北。只呈現地平線以下，照片只保留在本次分頁記憶體。</p><input id="panorama-file" type="file" accept="image/jpeg,image/png"><label>照片左邊緣方位角 <input id="panorama-north" type="number" min="0" max="359" value="0"></label><p>山脈高於地平線的輪廓尚不支援遮擋；不是自動下載所在地照片。</p>`);$('#panorama-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;if(file.size>15000000){toast('照片上限 15 MB');return;}const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);if(Math.abs(img.width/img.height-2)>.1){toast('請選擇 2:1 全景照片');return;}const c=document.createElement('canvas');c.width=1024;c.height=512;const g=c.getContext('2d');g.drawImage(img,0,0,1024,512);panorama={data:g.getImageData(0,0,1024,512).data,north:C.wrap(Number($('#panorama-north')?.value)||0)};state.layers.landscape=true;state.layers.ground=true;change();close();toast('現場地景已載入');};img.onerror=()=>{URL.revokeObjectURL(url);toast('照片無法解碼');};img.src=url;});}
 function background(g,w,h){if(stream)hud();if(stream){g.clearRect(0,0,w,h);return;}if(!state.layers.daylight)return;const altitude=pos('Sun').alt,k=C.clamp((altitude+18)/30,0,1);if(k){const gradient=g.createLinearGradient(0,0,0,h);gradient.addColorStop(0,`rgba(35,112,192,${k})`);gradient.addColorStop(1,`rgba(158,194,213,${k})`);g.fillStyle=gradient;g.fillRect(0,0,w,h);}}
 function draw(g,w,h,rotate,drawPath){if(state.layers.equatorial){for(let ra=0;ra<360;ra+=30)drawPath(Array.from({length:89},(_,i)=>rotate(C.equatorial(ra,i*2-88))),'#85dbcf60',.7,[3,4],false);for(let dec=-60;dec<=60;dec+=30)drawPath(Array.from({length:181},(_,i)=>rotate(C.equatorial(i*2,dec))),'#85dbcf60',.7,[3,4],false);}
 if(state.layers.bounds)for(const f of SKY_DATA.bounds)for(const ring of f.geometry.coordinates){const points=[];for(let j=1;j<ring.length;j++){const a=ring[j-1],b=ring[j],delta=((b[0]-a[0]+540)%360)-180,n=Math.max(1,Math.ceil(Math.max(Math.abs(delta),Math.abs(b[1]-a[1]))/2));for(let i=0;i<=n;i++)points.push(rotate(C.equatorial(a[0]+delta*i/n,a[1]+(b[1]-a[1])*i/n)));}drawPath(points,'#e1b88977',1,[3,5]);}
 if(state.layers.art){const sketches=[['Cyg',310,40,[[0,-1],[.2,-.2],[1,.5],[.3,.3],[0,1],[-.3,.3],[-1,.5],[-.2,-.2],[0,-1]]],['Aql',298,8,[[0,-1],[.2,-.4],[1,0],[.7,.3],[.2,.1],[0,1],[-.2,.1],[-.7,.3],[-1,0],[-.2,-.4],[0,-1]]],['Lyr',282,36,[[-.5,-.8],[-.8,-.5],[-.5,1],[.5,1],[.8,-.5],[.5,-.8],[.4,.8],[-.4,.8],[-.5,-.8]]],['Ori',84,-1,[[0,-1],[-.3,-.6],[.3,-.6],[0,-1],[0,-.4],[-.7,-.4],[-1,-1],[-.7,-.4],[0,-.1],[.8,-.5],[1,-1],[.8,-.5],[0,-.1],[0,.4],[-.5,1],[0,.4],[.5,1]]]];for(const [id,ra,dec,path] of sketches)drawPath(path.map(([x,y])=>rotate(C.equatorial(ra+x*8/Math.cos(dec*D),dec-y*10))),'#c8c0e67a',2);}}
 function foreground(g,w,h){if(!panorama||!state.layers.landscape||stream)return;const b=C.cameraBasis?C.cameraBasis(state.camera.az,state.camera.alt):null;if(!b)return;const scale=w/(4*Math.tan(state.camera.fov*D/4));for(let y=0;y<h;y+=6)for(let x=0;x<w;x+=6){const xx=(x-w/2)/scale,yy=-(y-h/2)/scale,r2=(xx*xx+yy*yy)/4,z=(1-r2)/(1+r2),rx=xx/(1+r2),uy=yy/(1+r2),v=b.f.map((n,i)=>n*z+b.r[i]*rx+b.u[i]*uy);if(v[1]>=0)continue;const az=C.wrap(Math.atan2(v[0],v[2])/D-panorama.north),alt=Math.asin(C.clamp(v[1],-1,1))/D,px=Math.floor(az/360*1024)%1024,py=Math.min(511,Math.floor((90-alt)/180*512)),i=(py*1024+px)*4;g.fillStyle=`rgb(${panorama.data[i]},${panorama.data[i+1]},${panorama.data[i+2]})`;g.fillRect(x,y,6,6);}}
 function arPanel(){modal('手機指向與相機 AR',`<p id="ar-location">位置：${esc(state.place.name)}（${state.place.lat.toFixed(5)}, ${state.place.lon.toFixed(5)}）。</p><button class="secondary" data-action="locate-now">重新定位／查看誤差</button><p>先設定正確位置。開啟後使用現在時間，關閉時間播放。相機影像只在裝置顯示，不上傳、不錄影。</p><p>請在 HTTPS 網站上，以 Safari／Chrome 開啟並授權。磁場與鏡頭視野會影響對準精度。</p><div class="dialog-actions"><button class="primary" data-advanced="sensor">啟用手機指向</button><button class="primary" data-advanced="camera">開啟相機疊圖</button><button class="secondary" data-advanced="stop">停止相機與感測器</button></div><p id="sensor-state">${esc(sensorMessage)}</p><p id="camera-state">相機：${stream?'已開啟':'未開啟'}</p><p>相機畫面與方向感測是兩個步驟；未取得可靠方向時，不會疊加東西南北或星體。</p><p>校正：遠離磁鐵，依裝置提示移動手機，再將畫面中心對準已知的正北地平線，按「校正正北」。也可對準目前選取的天體校正。校正偏移只保留於本次使用。</p><button class="secondary" data-advanced="calibrate">校正正北</button><button class="secondary" data-advanced="calibrate-star">對準選取天體校正</button><label>已知鏡頭方位（北 0°、東 90°、南 180°、西 270°）<input id="ar-bearing" type="number" min="0" max="359.9" step="0.1" value="270"></label><button class="secondary" data-advanced="calibrate-bearing">以此方位校正</button><label>水平鏡頭視野（依實際畫面調整）<input id="ar-fov" type="range" min="30" max="100" value="${state.camera.fov}"></label><button class="primary" data-action="close">回星空查看</button>`);$('#ar-fov').addEventListener('input',e=>{state.camera.fov=Number(e.target.value);change();});}
 function sensorStatus(s){sensorMessage=s;if($('#sensor-state'))$('#sensor-state').textContent=s;hud();}
 function unaligned(){return !!stream&&(!sensing||!lastOrientation||Date.now()-lastSensor>2500||(!calibrated&&Date.now()>absoluteUntil));}
 function hud(){let el=$('#ar-live-status');if(!stream&&!sensing){el?.remove();return;}if(!el){el=document.createElement('div');el.id='ar-live-status';el.setAttribute('role','status');canvas.parentElement.append(el);}const sun=pos('Sun');el.textContent=`${stream?'相機已開啟':'相機未開啟'} · ${sensorMessage}｜位置 ${state.place.lat.toFixed(4)}, ${state.place.lon.toFixed(4)}｜太陽參考：方位 ${sun.az.toFixed(1)}°、高度 ${sun.alt.toFixed(1)}°${sun.alt<0?'（地平線下）':''}`;}

 function sensorEvent(e){if(!sensing||![e.alpha,e.beta,e.gamma].every(Number.isFinite))return;
 // Relative Euler alpha is NOT interchangeable with webkitCompassHeading.
 // Keep relative orientation coherent and require a known-bearing calibration on Safari.
 if(!e.absolute&&Date.now()<absoluteUntil)return;
 if(Date.now()-lastSensorPaint<100)return;lastSensorPaint=Date.now();
 const q=orientation(e.alpha,e.beta,e.gamma,root.screen?.orientation?.angle??root.orientation??0);lastOrientation=q;lastSensor=Date.now();
 if(e.absolute){absoluteUntil=Date.now()+2500;sensorMessage='絕對方向已取得，請確認校正';}else sensorMessage=calibrated?'相對方向已校正':`相對方向待校正${Number.isFinite(e.webkitCompassHeading)?'（裝置羅盤 '+Math.round(e.webkitCompassHeading)+'°）':''}`;
 state.camera.az=C.wrap(q.az+offset);state.camera.alt=C.clamp(q.alt,-89,89);state.camera.roll=q.roll;state.track=false;setTime(Date.now());sensorStatus(sensorMessage);
 }
 async function startSensor(){if(sensing)return;if(!root.isSecureContext)throw Error('請使用 HTTPS，或此電腦的 localhost');if(!root.DeviceOrientationEvent)throw Error('裝置不支援方向感測器，仍可手動操作星圖');const token=session;if(typeof root.DeviceOrientationEvent.requestPermission==='function'){const result=await root.DeviceOrientationEvent.requestPermission(true);if(result!=='granted')throw Error('方向感測器權限未允許');}if(token!==session)return;sensing=true;state.playing=false;state.track=false;root.addEventListener('deviceorientation',sensorEvent);root.addEventListener('deviceorientationabsolute',sensorEvent);sensorStatus('等待感測資料，請拿起手機');sensorTimer=setTimeout(()=>{if(sensing&&!lastSensor)sensorStatus('沒有收到感測資料；請確認裝置支援，或停止後手動操作');},5000);}
 async function camera(){if(!root.isSecureContext||!navigator.mediaDevices?.getUserMedia)throw Error('相機需要 HTTPS 與支援的瀏覽器');const token=++session;const acquired=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});if(token!==session){acquired.getTracks().forEach(t=>t.stop());return;}if(stream)stream.getTracks().forEach(t=>t.stop());stream=acquired;let v=$('#ar-video');if(!v){v=document.createElement('video');v.id='ar-video';v.muted=true;v.autoplay=true;v.playsInline=true;canvas.parentElement.insertBefore(v,canvas);}v.srcObject=stream;try{await v.play();}catch(e){stop();throw Error('相機無法播放，請重新啟用');}state.camera.perspective=true;state.camera.fov=60;state.playing=false;setTime(Date.now());if($('#camera-state'))$('#camera-state').textContent='相機：已開啟';sensorStatus(sensing?sensorMessage:'方向尚未啟用，請按「啟用手機指向」');}
 function stop(){session++;sensing=false;clearTimeout(sensorTimer);root.removeEventListener('deviceorientation',sensorEvent);root.removeEventListener('deviceorientationabsolute',sensorEvent);stream?.getTracks().forEach(t=>t.stop());stream=null;$('#ar-video')?.remove();delete state.camera.roll;delete state.camera.perspective;lastSensor=0;lastOrientation=null;offset=0;calibrated=false;absoluteUntil=0;change();sensorStatus('相機與感測器已停止');}
 root.addEventListener('pagehide',stop);document.addEventListener('visibilitychange',()=>{if(document.hidden&&(sensing||stream))stop();});
 document.addEventListener('click',async e=>{const b=e.target.closest('[data-advanced]');if(!b)return;try{switch(b.dataset.advanced){case'unit':labOpen(b.dataset.unit);break;case'rise':modal('升落時間',`<p style="white-space:pre-line">${esc(riseSet())}</p>`);break;case'landscape':landscape();break;case'ar':arPanel();break;case'sensor':await startSensor();break;case'camera':await camera();break;case'stop':stop();break;case'calibrate-bearing':case'calibrate':case'calibrate-star':if(!lastOrientation)throw Error('尚未收到感測資料');{const bearing=b.dataset.advanced==='calibrate'?0:b.dataset.advanced==='calibrate-bearing'?Number($('#ar-bearing').value):pos().az;if(!Number.isFinite(bearing)||bearing<0||bearing>=360)throw Error('請輸入 0 至 359.9 度');if(b.dataset.advanced==='calibrate-star'&&state.selected==='Sun')throw Error('請使用已知地標方位校正，勿直視太陽');offset=C.wrap(bearing-lastOrientation.az);calibrated=true;state.camera.az=C.wrap(lastOrientation.az+offset);change();}sensorStatus('方向校正完成；請確認高度角與鏡頭視野');break;case'step':setTime(state.time+Number(b.dataset.days)*86400000);paintLab();break;case'eclipse':eclipse();break;case'preset':setTime(Date.parse(lab==='retro'?'2025-01-15T12:00:00Z':'2026-03-03T11:33:40Z'));paintLab();break;case'lab-reset':state.place={...base.place};state.camera={...base.camera};setTime(Date.parse(base.time));change();renderLab();break;case'lab-save':if(!prediction.trim()||!answer.trim())throw Error('請先完成預測與觀測解釋');download('AstroEdu-experiment.json',JSON.stringify({v:1,unit:lab,prediction,answer,before:base,after:snapshot(),measurements:$('#lab-values').textContent,event:$('#event-details').textContent},null,2));toast('實驗紀錄已匯出');break;}}catch(err){toast(err.message||String(err));}});
 return {open,arPanel,background,draw,foreground,unaligned,active:()=>!!stream||sensing};
};
})(globalThis);
