(() => {
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],C=SkyCore,A=window.Astronomy;
const theme=document.documentElement.dataset.theme;
const paths={compass:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18Z M16 8l-3 5-5 3 3-5 5-3Z',book:'M12 5C8 2 3 4 3 4v15s5-2 9 1c4-3 9-1 9-1V4s-5-2-9 1v15',note:'M15 3H5v18h14V9 M15 3v6h6L15 3Z M8 12h7 M8 16h5',search:'M11 3a8 8 0 1 0 0 16 8 8 0 0 0 0-16Z M17 17l5 5',moon:'M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11Z',help:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18Z M9 9a3 3 0 0 1 6 0c0 2-3 2-3 4 M12 16h.01',layers:'M3 8l9-5 9 5-9 5-9-5Z M3 12l9 5 9-5 M3 16l9 5 9-5',pin:'M12 22s8-8 8-13A8 8 0 0 0 4 9c0 5 8 13 8 13Z M12 6a3 3 0 1 0 0 6 3 3 0 0 0 0-6Z',plus:'M12 5v14 M5 12h14',minus:'M5 12h14',expand:'M8 3H3v5 M16 3h5v5 M3 16v5h5 M21 16v5h-5',target:'M12 5a7 7 0 1 0 0 14 7 7 0 0 0 0-14Z M12 1v6 M12 17v6 M1 12h6 M17 12h6',chevron:'M9 5l7 7-7 7',bulb:'M8 16C2 10 6 3 12 3s10 7 4 13v3H8v-3Z M9 22h6 M9 16h6',reset:'M4 11a8 8 0 1 1 1 6 M4 4v7h7',clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18Z M12 7v5l4 2',calendar:'M5 5h14v16H5V5Z M5 10h14 M8 2v6 M16 2v6',previous:'M6 5v14 M18 5l-10 7 10 7V5Z',next:'M18 5v14 M6 5l10 7-10 7V5Z',play:'M8 4l12 8-12 8V4Z',pause:'M8 5v14 M16 5v14',share:'M17 3l4 4-4 4 M21 7h-9v9 M5 9H3v12h16v-6',camera:'M3 7h5l2-3h4l2 3h5v14H3V7Z M12 10a4 4 0 1 0 0 8 4 4 0 0 0 0-8Z',close:'M5 5l14 14 M19 5L5 19',check:'M5 12l4 4L19 6'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[n]||paths.compass}"/></svg>`;
function icons(scope=document){scope.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));}
icons();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const named={91262:['織女星','Vega','天琴座','夏季大三角的成員，明亮的藍白色恆星。試著觀察它在數小時內的位置變化。'],102098:['天津四','Deneb','天鵝座','夏季大三角的成員，也是天鵝座的尾部。和織女星、牛郎星分屬三個星座。'],97649:['牛郎星','Altair','天鷹座','夏季大三角的成員。牛郎星與兩旁的河鼓一、河鼓三，形成容易辨認的排列。'],11767:['北極星','Polaris','小熊座','接近北天極，可用來辨認北方。它在天空中的高度與觀測者緯度有關。'],32349:['天狼星','Sirius','大犬座','夜空中視星等最亮的恆星，屬於冬季星空的醒目目標。'],27989:['參宿四','Betelgeuse','獵戶座','獵戶座的紅色超巨星。比較它和參宿七的顏色。'],24436:['參宿七','Rigel','獵戶座','獵戶座的藍白色亮星，與參宿四形成明顯的星色對比。'],69673:['大角星','Arcturus','牧夫座','春季夜空中的橙色亮星，可沿北斗斗柄的弧線尋找。'],65474:['角宿一','Spica','室女座','春季星空的藍白色亮星。大角星與角宿一是春季尋星的重要路標。'],80763:['心宿二','Antares','天蠍座','天蠍座中的紅色亮星，是夏季南方星空的醒目目標。'],37826:['北河三','Pollux','雙子座','雙子座中的橙色亮星，可與北河二一起辨認。'],36850:['北河二','Castor','雙子座','與北河三相鄰，是雙子座的重要辨認星。'],24608:['五車二','Capella','御夫座','北方冬季星空中的明亮目標。'],113368:['北落師門','Fomalhaut','南魚座','秋季南方天空中醒目的亮星。'],21421:['畢宿五','Aldebaran','金牛座','金牛座的橙色亮星，位於畢宿星團附近的視線方向。'],62434:['十字架三','Mimosa','南十字座','南半球重要的尋星標誌之一。'],71683:['南門二','Rigil Kentaurus','半人馬座','南方星空的明亮恆星，在台北大多位於地平線下。']};
const cn={Lyr:'天琴座',Cyg:'天鵝座',Aql:'天鷹座',Ori:'獵戶座',UMi:'小熊座',UMa:'大熊座',Sco:'天蠍座',Boo:'牧夫座',Vir:'室女座',Gem:'雙子座',Tau:'金牛座',Aur:'御夫座',CMa:'大犬座',Cas:'仙后座',Leo:'獅子座',Peg:'飛馬座',And:'仙女座',Sgr:'人馬座',Crux:'南十字座',Cru:'南十字座',Psc:'雙魚座',Ari:'牡羊座',Cnc:'巨蟹座',Lib:'天秤座',Cap:'摩羯座',Aqr:'寶瓶座',Per:'英仙座',Cep:'仙王座',Dra:'天龍座'};
const stars=SKY_DATA.stars.map(s=>({id:String(s[0]),ra:s[1],dec:s[2],mag:s[3],bv:s[4],vec:C.equatorial(s[1],s[2]),name:named[s[0]]?.[0]||`HIP ${s[0]}`,en:named[s[0]]?.[1]||'',constellation:named[s[0]]?.[2]||'恆星',description:named[s[0]]?.[3]||'來自 XHIP 星表的恆星。方位與高度依選定時間、地點計算；星點大小為辨識用途。'}));
const starMap=new Map(stars.map(s=>[s.id,s]));
const bodies=[['Sun','太陽'],['Moon','月球'],['Mercury','水星'],['Venus','金星'],['Mars','火星'],['Jupiter','木星'],['Saturn','土星'],['Uranus','天王星'],['Neptune','海王星']].map(([id,name])=>({id,name,en:id,constellation:'太陽系',body:true,description:id==='Moon'?'拖動日期比較月相。月球亮面是受到太陽照射的部分；一般月相並非地球影子造成。':'位置依觀測時間與地點計算。星點及行星圓盤大小為辨識用途，並非實際角直徑。'}));
const dsos=(SKY_DATA.dsos||[]).map(f=>({id:f.id.replace(/\+/g,'P').replace(/-/g,'N').replace(/[^a-z0-9]/gi,''),name:f.id,en:f.properties.desig||f.id,ra:f.geometry.coordinates[0],dec:f.geometry.coordinates[1],vec:C.equatorial(...f.geometry.coordinates),mag:Number(f.properties.mag)||0,dso:true,constellation:'深空天體 · '+f.properties.type,description:'深空天體符號為辨識用途，非目視外觀。類型 '+f.properties.type+'，角大小 '+f.properties.dim+' 角分；資料來源 d3-celestial。'}));
const objects=new Map([...stars,...bodies,...dsos].map(s=>[s.id,s]));
const places=[{name:'台北',lat:25.033,lon:121.5654},{name:'台中',lat:24.1477,lon:120.6736},{name:'高雄',lat:22.6273,lon:120.3014},{name:'合歡山',lat:24.143,lon:121.284},{name:'赤道・新加坡',lat:1.3521,lon:103.8198},{name:'雪梨',lat:-33.8688,lon:151.2093},{name:'雷克雅維克',lat:64.1466,lon:-21.9426}];
const lessons={triangle:{title:'夏季大三角',tag:'星空觀測入門',intro:'三顆亮星，連起夏夜的路標。從織女星出發，找到天津四與牛郎星，認識它們各自的星座。',steps:['找到織女星','找到天津四','找到牛郎星','留下你的觀察'],instructions:['點選星圖中的織女星，或用搜尋找到它。','沿著銀河尋找天鵝座尾部的天津四。','尋找天鷹座的牛郎星，完成大三角。','將任一顆星加入筆記，寫下你的發現。'],hints:['搜尋「織女星」可以置中目標，再點擊星點。','天津四的英文名稱是 Deneb。','牛郎星的英文名稱是 Altair。','按下「加入觀測筆記」並儲存文字。']},motion:{title:'星星如何移動？',tag:'周日運動實驗',intro:'先預測，再播放。固定觀測位置與朝向，比較同一顆星在兩小時前後的高度與方位。',steps:['選取觀測目標','預測星空的變化','向前推進兩小時','記下觀測結果'],instructions:['選取任一顆恆星，記住它目前的位置。','你認為星星的方位或高度會改變嗎？','點下實驗按鈕，保持視角不動，比較前後位置。','記錄你發現的變化，並閱讀解釋。'],hints:['建議從織女星開始。','地球自轉會使星空在一夜之間呈現移動。','軌跡標記顯示不同時刻的方向，不代表星體真正繞地球運行。','把前後高度寫進筆記，保留實驗結果。']},seasons:{title:'四季的星空',tag:'季節比較實驗',intro:'固定地點與每天的鐘錶時間，改變月份。觀察夏季大三角是否仍在原本的位置。',steps:['選取比較目標','預測三個月後','切換三個月後','記錄季節差異'],instructions:['選取織女星或另一顆熟悉的星。','同一鐘錶時間，不同季節的星空會相同嗎？','向前切換三個月，保留地點與視角。','比較前後方位、高度與地平線可見性。'],hints:['先留意目標卡上的方位與高度。','地球公轉使夜晚朝向的星空隨季節改變。','這裡使用台灣時間，比較每天同一鐘錶時間。','目標可能移出畫面；搜尋後置中可檢查是否在地平線下。']},moon:{title:'月亮的盈與虧',tag:'月相觀察實驗',intro:'跟著月亮走過一週。觀察照明比例的改變，理解月相與太陽照射的關係。',steps:['選取月球','預測一週後月相','向前推進七天','記錄亮面的變化'],instructions:['搜尋「月球」並選取，觀察目前月相。','月球受到太陽照亮的部分，從地球看起來會一樣嗎？','向前七天，比較右側月相圖與照明比例。','記下兩次月相，以及亮面改變的原因。'],hints:['月球可能在地平線下，星圖會明確標示。','一般月相不是地球影子造成，只有月食才涉及地球的影子。','小圖使用北方朝上的示意方向，不等同目鏡實際旋轉角度。','兩次月相資料已保留於課程實驗摘要。']}};
const state={live:false,locationReady:false,moonGuide:false,time:Date.now(),place:{...places[0]},camera:{az:70,alt:55,fov:83},layers:{lines:true,labels:true,grid:false,ecliptic:false,ground:true,milky:false,trails:false,night:false,dso:false,bounds:false,art:false,equatorial:false,daylight:true,landscape:false},lesson:'triangle',selected:'91262',playing:false,rate:60,track:false,found:new Set(),completed:0,prediction:null,baseline:null,experiment:false};
let storageAvailable=true,notes=[];const storeKey=`astroedu-${theme}-notes-v1`;
try{notes=JSON.parse(localStorage.getItem(storeKey)||'[]');if(!Array.isArray(notes))notes=[];notes=notes.filter(n=>n&&typeof n.text==='string'&&typeof n.id==='string').slice(0,500);}catch{storageAvailable=false;}
let advanced=null;
const canvas=$('#sky'),ctx=canvas.getContext('2d',{alpha:true});let w=0,h=0,dpr=1,rot=null,cacheTime=null,positions=[],hits=[],dirty=true,lastUI=0,lastFrame=0,lastRender=0,toastTimer;
const coordLines=SKY_DATA.lines.map(f=>({id:f.id,paths:f.paths.map(line=>line.map(p=>C.equatorial(...p)))}));
const mw=SKY_DATA.milky.map(f=>f.map(ring=>ring.map(p=>C.equatorial(...p))));
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3600);}
const twDate=t=>new Date(t+8*3600000).toISOString();
const fmt=t=>twDate(t).slice(0,16).replace('T',' ');
const observer=()=>new A.Observer(state.place.lat,state.place.lon,0);
function rotate(v,m=rot){return [-(m[0][1]*v[0]+m[1][1]*v[1]+m[2][1]*v[2]),m[0][2]*v[0]+m[1][2]*v[1]+m[2][2]*v[2],m[0][0]*v[0]+m[1][0]*v[1]+m[2][0]*v[2]];}
function fromVector(vec){return {vec,az:C.wrap(Math.atan2(vec[0],vec[2])/C.D),alt:Math.asin(C.clamp(vec[1],-1,1))/C.D};}
function updatePositions(){
 if(cacheTime===state.time)return;
 rot=A.Rotation_EQJ_HOR(new Date(state.time),observer()).rot;
 positions=[...stars,...dsos].map(s=>({...fromVector(rotate(s.vec)),object:s}));
 const date=new Date(state.time),ob=observer();
 for(const b of bodies){const eq=A.Equator(b.id,date,ob,true,true),hor=A.Horizon(date,ob,eq.ra,eq.dec);b.ra=eq.ra*15;b.dec=eq.dec;b.mag=A.Illumination(b.id,date).mag;b.position={az:hor.azimuth,alt:hor.altitude,vec:C.altAzVector(hor.azimuth,hor.altitude)};positions.push({...b.position,object:b});}
 cacheTime=state.time;
}
function pos(id=state.selected){updatePositions();return positions.find(p=>p.object.id===String(id));}
function setTime(t){if(!Number.isFinite(t))return;state.time=C.clamp(t,Date.UTC(2000,0,1),Date.UTC(2050,11,31,15,59));dirty=true;updateUI();}
function viewTarget(id=state.selected){const p=pos(id);if(!p)return;state.camera.az=p.az;state.camera.alt=C.clamp(p.alt,-89,89);dirty=true;}
function focusTriangle(){updatePositions();const v=['91262','102098','97649'].map(id=>pos(id).vec).reduce((a,b)=>a.map((x,i)=>x+b[i]),[0,0,0]);const norm=Math.hypot(...v),p=fromVector(v.map(x=>x/norm));state.camera={az:p.az,alt:C.clamp(p.alt,-89,89),fov:83};dirty=true;}
function snapshot(){return {v:1,time:new Date(state.time).toISOString(),place:{...state.place},camera:{...state.camera},layers:{...state.layers},lesson:state.lesson,selected:state.selected};}
function applyScene(s){manualMode();s=C.validScene(s);state.time=Date.parse(s.time);state.place=s.place;state.camera=s.camera;state.layers=s.layers;state.lesson=s.lesson;state.selected=objects.has(s.selected)?s.selected:'91262';state.playing=false;state.track=false;resetProgress();cacheTime=null;dirty=true;updateUI();renderLesson();}
function drawPath(vecs,color,width=1,dash=[],ground=true){ctx.beginPath();let prev=null;for(const v of vecs){const p=C.project(v,state.camera,w,h);if(!p||(ground&&state.layers.ground&&v[1]<0)){prev=null;continue;}if(prev&&Math.hypot(p.x-prev.x,p.y-prev.y)<w*.65)ctx.lineTo(p.x,p.y);else ctx.moveTo(p.x,p.y);prev=p;}ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.stroke();ctx.setLineDash([]);}
function starDraw(x,y,r,color,bright){if(bright){let g=ctx.createRadialGradient(x,y,0,x,y,r*8);g.addColorStop(0,color+'99');g.addColorStop(.2,color+'33');g.addColorStop(1,color+'00');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r*8,0,Math.PI*2);ctx.fill();ctx.strokeStyle=color+'88';ctx.lineWidth=.6;ctx.beginPath();ctx.moveTo(x-r*3,y);ctx.lineTo(x+r*3,y);ctx.moveTo(x,y-r*3);ctx.lineTo(x,y+r*3);ctx.stroke();}ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}
function draw(){
 if(!w||!h)return;updatePositions();if(state.track)viewTarget();
 ctx.setTransform(dpr,0,0,dpr,0,0);const bg=ctx.createLinearGradient(0,0,w,h);bg.addColorStop(0,theme==='C'?'#070c22':'#030b16');bg.addColorStop(.5,'#07172b');bg.addColorStop(1,'#091421');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);hits=[];advanced?.background(ctx,w,h);if(advanced?.unaligned()){dirty=false;return;}
 const proj=v=>C.project(v,state.camera,w,h);
 if(state.layers.milky){ctx.save();ctx.globalAlpha=.08;mw.forEach((rings,i)=>{ctx.fillStyle=['#6389ba','#7190b5','#9caec7','#adbed5','#cfdae8'][i%5];for(const ring of rings){ctx.beginPath();let active=false,count=0;for(const v of ring){const vv=rotate(v),p=proj(vv);if(!p||Math.abs(p.x)>w*3||Math.abs(p.y)>h*5){if(count>3){ctx.closePath();ctx.fill();}ctx.beginPath();active=false;count=0;continue;}if(!active){ctx.moveTo(p.x,p.y);active=true;}else ctx.lineTo(p.x,p.y);count++;}if(count>3){ctx.closePath();ctx.fill();}}});ctx.restore();}
 if(state.layers.grid){for(let az=0;az<360;az+=30)drawPath(Array.from({length:89},(_,i)=>C.altAzVector(az,i*2-88)),'#abc6de26',.7,[],false);for(let alt=-60;alt<=60;alt+=30)drawPath(Array.from({length:181},(_,i)=>C.altAzVector(i*2,alt)),'#abc6de26',.7,[],false);}
 if(state.layers.ecliptic){const m=A.Rotation_ECL_EQJ();const v=Array.from({length:361},(_,i)=>{const p=A.RotateVector(m,new A.Vector(Math.cos(i*C.D),Math.sin(i*C.D),0,new Date(state.time)));return rotate([p.x,p.y,p.z]);});drawPath(v,'#e3b77988',1,[5,6],false);}
 if(state.layers.lines){for(const f of coordLines)for(const line of f.paths)drawPath(line.map(v=>rotate(v)),'#719dc14f',.7);}
 advanced?.draw(ctx,w,h,rotate,drawPath);
 const placed=[];const selected=pos(),sunAltitude=pos("Sun").alt;
 for(const p of positions){const s=p.object;if(s.dso&&s.id!==state.selected&&(!state.layers.dso||s.mag>Math.min(10,6+Math.max(0,60-state.camera.fov)/12)))continue;if(state.layers.daylight&&sunAltitude>0&&!s.body&&s.mag>-2)continue;if(state.layers.ground&&p.alt<0)continue;const screen=proj(p.vec);if(!screen||screen.x<-20||screen.y<-20||screen.x>w+20||screen.y>h+20)continue;
 const namedStar=!!named[s.id],big=s.id==='Sun'?10:s.body?3:s.mag<1.5?2.5:s.mag<3?1.4:.5+(6-s.mag)*.16;
 const r=big*Math.min(1.4,Math.sqrt(85/state.camera.fov));const color=s.body?(s.id==='Sun'?'#ffcb6b':s.id==='Mars'?'#eeab82':'#ebddc3'):s.bv>.9?'#f3c58d':s.bv>.3?'#ece5d5':'#cce8ff';
 if(s.dso){ctx.strokeStyle='#9fe2ba';ctx.lineWidth=1.2;ctx.beginPath();ctx.ellipse(screen.x,screen.y,7,4,-.4,0,Math.PI*2);ctx.stroke();}else starDraw(screen.x,screen.y,r,color,s.mag<2||namedStar||s.body);if(s.dso||s.mag<4||namedStar||s.body)hits.push({...screen,id:s.id,mag:s.mag});
 if(state.layers.labels&&(s.dso||namedStar||s.body||s.id===state.selected))placed.push({p:screen,s,color});
 }
 if(state.layers.lines&&state.lesson==='triangle'){const tri=['91262','102098','97649','91262'].map(id=>pos(id).vec);drawPath(tri,theme==='C'?'#c1bbe0b0':'#edc789bd',1,[6,5]);const ps=tri.slice(0,3).map(proj);if(ps.every(p=>p&&p.x>0&&p.x<w&&p.y>0&&p.y<h)){const x=ps.reduce((s,p)=>s+p.x,0)/3,y=ps.reduce((s,p)=>s+p.y,0)/3;ctx.font=`500 ${w<500?15:19}px system-ui`;ctx.textAlign='center';ctx.fillStyle=theme==='C'?'#e7dbff':'#f5d59d';ctx.fillText('夏 季 大 三 角',x,y);ctx.font='10px system-ui';ctx.fillStyle='#b7c2d0';ctx.fillText('S U M M E R   T R I A N G L E',x,y+22);}}
 if(state.layers.trails&&selected&&!selected.object.body){const vec=selected.object.vec,ob=observer();const points=Array.from({length:49},(_,i)=>rotate(vec,A.Rotation_EQJ_HOR(new Date(state.time+(i-24)*300000),ob).rot));drawPath(points,'#edae73',1.2,[4,4]);for(const i of [0,24,48]){const p=proj(points[i]);if(p){ctx.fillStyle='#f6c593';ctx.font='10px system-ui';ctx.textAlign='left';ctx.fillText(`${(i-24)/12>0?'+':''}${(i-24)/12}h`,p.x+7,p.y-7);}}}
 if(state.layers.ground){const horizon=Array.from({length:361},(_,i)=>C.altAzVector(i,0));drawPath(horizon,'#8ca9b466',1,[],false);for(let az=0;az<360;az+=45){const p=proj(C.altAzVector(az,0));if(p&&p.x>0&&p.x<w&&p.y>0&&p.y<h){ctx.fillStyle='#a8c3cf';ctx.font='11px system-ui';ctx.textAlign='center';ctx.fillText(['北 N','東北','東 E','東南','南 S','西南','西 W','西北'][az/45],p.x,p.y+19);}}}
 if(selected){const p=proj(selected.vec);if(p&&(!state.layers.ground||selected.alt>=0)){ctx.strokeStyle=theme==='C'?'#ffc2b3':'#81dcfc';ctx.lineWidth=1;ctx.beginPath();ctx.arc(p.x,p.y,17,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(p.x,p.y,22,.1,.65);ctx.arc(p.x,p.y,22,Math.PI+.1,Math.PI+.65);ctx.stroke();}}
 const boxes=[];placed.sort((a,b)=>(a.s.id===state.selected?-1:b.s.id===state.selected?1:a.s.mag-b.s.mag));
 for(const {p,s} of placed){const fs=w<500?12:14;ctx.font=`500 ${fs}px system-ui`;const tw=ctx.measureText(s.name).width;let x=p.x+14,y=p.y-10;if(x+Math.max(tw,70)>w-12)x=p.x-Math.max(tw,70)-16;
 const box={x,y:y-17,w:Math.max(tw,75),h:42};if(y<130&&x<280||x>w-65&&y<270||y>h-70)continue;if(boxes.some(b=>box.x<b.x+b.w&&box.x+box.w>b.x&&box.y<b.y+b.h&&box.y+box.h>b.y))continue;boxes.push(box);ctx.textAlign='left';ctx.lineWidth=4;ctx.strokeStyle='#05101bc0';ctx.strokeText(s.name,x,y);ctx.fillStyle='#e9f4ff';ctx.fillText(s.name,x,y);ctx.font='10px system-ui';ctx.fillStyle='#adbbcc';ctx.fillText(s.en,x,y+17);}
 advanced?.foreground(ctx,w,h);ctx.textAlign='left';dirty=false;
}
function resize(){const r=canvas.getBoundingClientRect();w=r.width;h=r.height;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);dirty=true;}
function updateUI(){
 updatePositions();$('#scene-date').textContent=fmt(state.time);$('#date-display').textContent=fmt(state.time);$('#scene-place').textContent=state.place.name;$('#view-direction').textContent=advanced?.unaligned()?'方向未校正 · 請完成開始觀星':`${C.directionName(state.camera.az)} ${Math.round(state.camera.az)}° ｜ 仰角 ${Math.round(state.camera.alt)}°`;$('#view-fov').textContent=`視野 ${state.camera.fov.toFixed(0)}°`;
 $('#play-status').textContent=state.playing?`時間播放中 · ${state.rate}×`:(state.live?'即時觀星 · '+(state.locationReady?'位置已設定':'等待定位'):'手動／教學模擬');updateObservation();$('#play-button').innerHTML=icon(state.playing?'pause':'play');$('#play-button').setAttribute('aria-label',state.playing?'暫停時間':'播放時間');const local=new Date(state.time+28800000);$('#time-range').value=local.getUTCHours()*60+local.getUTCMinutes();$('#speed').value=String(state.rate);
 document.documentElement.classList.toggle('night',state.layers.night);const p=pos(),s=p.object;
 $('#target-name').innerHTML=`${esc(s.name)} <small>${esc(s.en)}</small>`;$('#object-id').textContent=s.body?'SOLAR SYSTEM':s.dso?s.id:`HIP ${s.id}`;$('#target-subtitle').textContent=`${s.constellation} · ${p.alt>=0?'地平線上':'地平線下'}`;$('#target-description').textContent=s.description;
 const lunar=s.id==='Moon';let phase=lunar?A.MoonPhase(new Date(state.time)):null;
 $('#target-metrics').innerHTML=`<div>${lunar?'照明比例':'視星等'}<strong>${lunar?Math.round((1-Math.cos(phase*C.D))*50)+'%':(s.mag>=99?'未提供':s.mag.toFixed(2))}</strong></div><div>方位角<strong>${p.az.toFixed(1)}°</strong></div><div>高度角<strong>${p.alt.toFixed(1)}°</strong></div>`;
 $('#target-visual').innerHTML=lunar?'<canvas id="moon-thumb" width="132" height="132" style="width:62px;height:62px"></canvas>':'✦';if(lunar)drawMoon($('#moon-thumb'),phase);
 $('[data-action=track]').classList.toggle('active',state.track);$('[data-action=track]').setAttribute('aria-pressed',state.track);
 if(state.lesson==='moon'){const cv=$('#phase-canvas');if(cv){phase=A.MoonPhase(new Date(state.time));drawMoon(cv,phase);$('#phase-info').innerHTML=`${C.phaseName(phase)}<p>照明 ${Math.round((1-Math.cos(phase*C.D))*50)}% · 北方朝上示意</p>`;}}
}
function drawMoon(cv,phase){if(!cv)return;const g=cv.getContext('2d'),size=cv.width,r=size*.43,c=size/2;g.clearRect(0,0,size,size);g.fillStyle='#111826';g.beginPath();g.arc(c,c,r,0,Math.PI*2);g.fill();const im=g.getImageData(0,0,size,size),angle=phase*C.D;for(let y=0;y<size;y++)for(let x=0;x<size;x++){const nx=(x-c)/r,ny=(y-c)/r,rr=nx*nx+ny*ny;if(rr>1)continue;const z=Math.sqrt(1-rr),light=nx*Math.sin(angle)-z*Math.cos(angle),idx=(y*size+x)*4;const shade=light>0?Math.round(170+65*z):23;im.data[idx]=shade;im.data[idx+1]=shade+Math.min(7,255-shade);im.data[idx+2]=Math.min(255,shade+12);im.data[idx+3]=255;}g.putImageData(im,0,0);}
function resetProgress(){state.found=new Set();state.completed=0;state.prediction=null;state.baseline=null;state.experiment=false;}
function progress(){if(state.lesson==='triangle'){let n=0;for(const id of ['91262','102098','97649']){if(state.found.has(id))n++;else break;}return n===3&&state.completed===4?4:n;}return state.completed;}
function renderLesson(){const lesson=lessons[state.lesson],n=progress();$('#lesson-title').textContent=lesson.title;$('.sky-title h1').textContent=lesson.title;$('.lesson-tag').textContent=lesson.tag;$('#lesson-intro').textContent=lesson.intro;$('#progress-number').textContent=n;$('.progress-bars').setAttribute('aria-label',`課程完成 ${n} / 4`);$$('.progress-bars i').forEach((e,i)=>e.classList.toggle('done',i<n));
 $('#mission-list').innerHTML=lesson.steps.map((title,i)=>`<div class="mission-step ${i<n?'done':i===n?'current':''}"><span class="step-number">${i<n?'✓':String(i+1).padStart(2,'0')}</span><div><strong>${title}</strong><p>${lesson.instructions[i]}</p>${i===n&&state.lesson!=='triangle'&&i===1?'<div class="choice-list"><button class="secondary" data-action="predict" data-value="change">會改變</button><button class="secondary" data-action="predict" data-value="same">不會改變</button></div>':''}${i===n&&i===2&&state.lesson!=='triangle'?'<button class="primary" data-action="experiment">開始比較 '+icon('chevron')+'</button>':''}${i===n&&i===3?'<button class="primary" data-action="save-note">記錄觀察 '+icon('note')+'</button>':''}</div></div>`).join('')+(n===4?'<div class="hint-text">✓ 課程完成！你可以重設再試，或探索下一個單元。</div>':'');
 $('#lesson-extra').innerHTML=state.lesson==='moon'?'<div class="phase-widget"><canvas id="phase-canvas" width="132" height="132"></canvas><div id="phase-info"></div></div>':'';
 if(state.baseline&&state.experiment){const p=pos(state.baseline.id);$('#lesson-extra').innerHTML+=`<p class="hint-text">比較前：${esc(state.baseline.date)}<br>高度 ${state.baseline.alt.toFixed(1)}° → ${p.alt.toFixed(1)}°${state.baseline.phase!==undefined?`<br>照明 ${state.baseline.phase}% → ${Math.round((1-Math.cos(A.MoonPhase(new Date(state.time))*C.D))*50)}%`:''}<br>${state.lesson==='motion'?'地球自轉造成星空的周日運動。':state.lesson==='seasons'?'地球公轉使同一時刻看見的星空隨季節改變。':'亮面變化來自日地月相對位置的改變。'}</p>`;}
 $('#found-count').textContent=`已找到 ${state.found.size} / 3`;$('#discovery-list').innerHTML=['91262','102098','97649'].map(id=>`<button data-action="select" data-id="${id}"><span class="${state.found.has(id)?'found':''}">${state.found.has(id)?'✓':'○'}</span>${named[id][0]} <small>${state.found.has(id)?'已找到':'待尋找'} · ${named[id][1]}</small></button>`).join('');$('#hint-text').hidden=true;updateUI();}
function select(id,center=true){if(!objects.has(String(id)))return;state.selected=String(id);state.track=false;if(['91262','102098','97649'].includes(state.selected))state.found.add(state.selected);
 if(state.lesson!=='triangle'&&state.completed===0&&(state.lesson!=='moon'||id==='Moon')){state.completed=1;const p=pos();state.baseline={id:state.selected,date:fmt(state.time),alt:p.alt,az:p.az,phase:state.lesson==='moon'?Math.round((1-Math.cos(A.MoonPhase(new Date(state.time))*C.D))*50):undefined};}
 if(center)viewTarget();dirty=true;renderLesson();if(pos().alt<0)toast('這個天體目前位於地平線下；可在圖層中關閉地平遮罩。');}
function modal(title,body){$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=body;icons($('#dialog'));if(!$('#dialog').open)$('#dialog').showModal();}
const close=()=>$('#dialog').close();
function search(){modal('探索星空',`<div class="search-field">${icon('search')}<input id="search-input" placeholder="星名、英文、HIP 編號或星座" aria-label="搜尋天體或星座" autocomplete="off"></div><div class="result-list" id="results"></div><p class="muted" style="font-size:11px;margin-top:15px">搜尋 5,044 顆恆星、3,311 個深空天體、88 個星座與日月行星。</p>`);const input=$('#search-input');input.addEventListener('input',()=>searchResults(input.value));searchResults('');input.focus();}
function searchResults(q){q=q.trim().toLowerCase();const matches=[...bodies,...dsos,...stars].filter(s=>q?`${s.name} ${s.en} ${s.en.replace(/ /g,'')} ${s.id} ${s.constellation} hip ${s.id}`.toLowerCase().includes(q):!!named[s.id]||s.id==='Moon').slice(0,25);const cons=q?coordLines.filter(f=>`${f.id} ${cn[f.id]||''}`.toLowerCase().includes(q)).slice(0,8):[];
 $('#results').innerHTML=cons.map(f=>`<button class="result-item" data-action="constellation" data-id="${f.id}"><span>⌁</span><span>${cn[f.id]||f.id}<small>${f.id} · 星座</small></span><span>查看星區</span></button>`).join('')+matches.map(s=>{const p=pos(s.id);return `<button class="result-item" data-action="search-select" data-id="${s.id}"><span>${s.body?'◉':'✦'}</span><span>${esc(s.name)}<small>${esc(s.en||'HIP '+s.id)} · ${esc(s.constellation)}</small></span><span>${p.alt>=0?'高度 '+p.alt.toFixed(0)+'°':'地平線下'}</span></button>`;}).join('')||'<div class="empty-state">找不到符合的天體。試試「織女星」、「月球」或 HIP 編號。</div>';}
function showCourses(){modal('選擇一段星空旅程',`<p>每個單元都能操作、觀察與記錄。切換課程會開始新的實驗，已儲存的筆記仍保留。</p><button class="primary" data-action="advanced">進階教學實驗室：3D、日月食、逆行與更多單元</button>${Object.entries(lessons).map(([id,l],i)=>`<button class="course-option ${id===state.lesson?'current':''}" data-action="load-lesson" data-id="${id}"><span class="course-number">0${i+1}</span><span><strong>${l.title}</strong><small>${l.tag} · 4 個步驟</small></span></button>`).join('')}`);}
function loadLesson(id){if(!lessons[id])return;const place={...state.place};if(id!=='moon')manualMode();state.lesson=id;state.playing=false;state.track=false;state.moonGuide=id==='moon';state.time=id==='moon'?Date.now():Date.parse('2026-07-15T13:00:00Z');state.place=id==='moon'?place:{...places[0]};cacheTime=null;state.selected=id==='moon'?'Moon':'91262';state.layers.trails=id==='motion';resetProgress();if(id!=='moon')focusTriangle();close();renderLesson();dirty=true;if(id==='moon'){state.live=true;updateUI();if(!advanced?.aligned())startDialog();}}
function layers(){const rows=[['lines','星座連線','顯示星座線條與夏季大三角'],['labels','天體名稱','亮星與日月行星標籤'],['grid','地平座標網','方位角與高度角參考線'],['ecliptic','黃道','太陽在天球上的年運動路徑'],['milky','銀河輪廓（示意）','可選的輪廓亮帶，非銀河照片'],['ground','地平遮罩','隱藏地平線下的天體'],['trails','周日運動軌跡','選取恆星前後兩小時的位置'],['dso','深空天體','依亮度及縮放篩選，避免符號重疊'],['bounds','星座邊界','88 星座天區邊界'],['art','星座插畫','原創線描：天鵝、天鷹、天琴、獵戶'],['equatorial','赤道座標網','J2000 赤經與赤緯'],['daylight','白天天空','依太陽高度呈現日光與曙暮光'],['landscape','現場地景','在進階工具匯入 2:1 全景照片'],['night','紅光夜間模式','降低介面亮度並改為暖紅色']];modal('調整你的星圖',rows.map(([key,title,desc])=>`<label class="toggle-row"><div><span>${title}</span><small>${desc}</small></div><input type="checkbox" data-layer="${key}" ${state.layers[key]?'checked':''}></label>`).join('')+'<p class="muted" style="font-size:11px;margin-top:15px">星點大小與銀河亮度為教學示意；此版未模擬大氣消光與折射。</p>');}
let geoRequest=0;
function manualMode(){geoRequest++;state.live=false;state.moonGuide=false;advanced?.stop();}
function startDialog(){modal('開始觀星',`<p>按下按鈕，允許「位置」與「動作和方向」，就能看到現在面前的星空。</p><button class="primary observe-start" data-action="start-observing">開始觀星 · 使用我的位置</button><p id="observe-status" role="status">AR 相機預設關閉；開啟後只增加實景背景。</p><p>iPhone／iPad 若提示校正，先將手機短暫平放、螢幕朝上，再拿起指向天空。</p><div class="dialog-actions"><button class="secondary" data-action="location">手動設定位置</button><button class="secondary" data-action="sensor-settings">方向設定</button><button class="secondary" data-action="manual-explore">先手動探索</button><button class="secondary" data-action="close">回星空</button></div>`);}
function beginObservation(){state.live=true;state.playing=false;state.track=false;state.camera.perspective=true;state.camera.fov=60;setTime(Date.now());const status=$('#observe-status'),button=$('[data-action=start-observing]');const report=t=>{if(status?.isConnected)status.textContent=t;toast(t);};advanced.startSensor().catch(e=>toast(e.message+'；可在方向設定重試，或先手動探索。'));if(button)button.disabled=true;state.locationReady=false;updateUI();const token=++geoRequest;let done=false;const finish=()=>{if(done||token!==geoRequest)return false;done=true;clearTimeout(timer);if(button)button.disabled=false;return true;};const timer=setTimeout(()=>{if(finish())report('定位超過 8 秒。請重試，或選「手動設定位置」。');},8000);if(status)status.textContent='正在取得位置，最多等待 8 秒…';if(!navigator.geolocation){finish();report('此瀏覽器無法定位，請選「手動設定位置」。');return;}navigator.geolocation.getCurrentPosition(p=>{if(!finish())return;const c=p.coords;if(!Number.isFinite(c.latitude)||!Number.isFinite(c.longitude)||Math.abs(c.latitude)>90||Math.abs(c.longitude)>180){report('裝置位置無效，請重試。');return;}state.place={name:'我的位置',lat:c.latitude,lon:c.longitude};state.locationReady=true;cacheTime=null;dirty=true;const accuracy=Number.isFinite(c.accuracy)?`約 ±${Math.round(c.accuracy)} 公尺`:'誤差未提供';report('位置已自動套用（'+accuracy+'）。'+(advanced.aligned()?'可回星空觀察。':'請依畫面提示完成方向校正，再回星空。'));updateUI();},e=>{if(finish())report(e.code===1?'位置權限未允許，請在瀏覽器允許定位，或手動設定位置。':'無法取得位置，請重試或手動設定位置。');},{timeout:8000,maximumAge:0,enableHighAccuracy:true});}
function updateObservation(){if(state.live)$('.sky-title h1').textContent=state.moonGuide?'尋找今晚的月亮':'現在面前的天空';const ar=$('[data-action=ar]');ar.setAttribute('aria-pressed',!!advanced?.cameraActive());ar.classList.toggle('active',!!advanced?.cameraActive());ar.title=advanced?.cameraActive()?'關閉相機背景，繼續指向觀星':'開啟相機背景';let guide=$('#moon-guide');if(!guide){guide=document.createElement('div');guide.id='moon-guide';guide.setAttribute('role','status');canvas.parentElement.append(guide);}guide.hidden=!state.moonGuide;if(!state.moonGuide)return;if(!state.locationReady){guide.textContent='尋找月亮：請先按「開始觀星」完成定位';return;}if(!advanced?.aligned()){guide.textContent='尋找月亮：請完成手機方向校正';return;}const moon=pos('Moon'),g=C.guideTarget(moon,state.camera);guide.innerHTML=g.kind==='below'?`☾ 月亮目前在地平線下（${moon.alt.toFixed(0)}°），現在無法看見`:g.kind==='found'?'☾ 已對準月亮！請看畫面中央':`<span class="moon-arrow" style="transform:rotate(${g.angle}deg)">↑</span><span>跟著箭頭轉動，尋找月亮<br>還差 ${Math.round(g.distance)}° · ${C.directionName(moon.az)}</span>`;}
function locationDialog(){modal('觀測位置',`<form id="location-form"><p id="geo-status" role="status">可使用裝置定位，或直接輸入經緯度。</p><label class="field"><span>選擇地點</span><select id="place-select"><option value="custom">自訂位置</option>${places.map((p,i)=>`<option value="${i}" ${p.name===state.place.name?'selected':''}>${p.name}</option>`).join('')}</select></label><label class="field"><span>地點名稱</span><input id="place-name" maxlength="60" value="${esc(state.place.name)}" required></label><div class="form-row"><label class="field"><span>緯度（北正南負）</span><input id="lat" type="number" step="any" min="-90" max="90" value="${state.place.lat}" required></label><label class="field"><span>經度（東正西負）</span><input id="lon" type="number" step="any" min="-180" max="180" value="${state.place.lon}" required></label></div><p class="muted" style="font-size:12px">所有地點的時間輸入統一顯示 UTC+08:00，方便課堂比較。</p><div class="dialog-actions"><button type="button" data-action="geolocate" class="secondary">${icon('pin')}使用我的位置</button><button class="primary" type="submit">套用位置</button></div></form>`);$('#place-select').addEventListener('change',e=>{const p=places[e.target.value];if(p){$('#place-name').value=p.name;$('#lat').value=p.lat;$('#lon').value=p.lon;}});$('#location-form').addEventListener('submit',e=>{e.preventDefault();state.place={name:$('#place-name').value.trim()||'自訂位置',lat:Number($('#lat').value),lon:Number($('#lon').value)};state.locationReady=true;cacheTime=null;state.track=false;close();dirty=true;updateUI();toast('已更新觀測位置');});}
function dateDialog(){modal('穿越時間',`<form id="date-form"><label class="field"><span>日期與時間 · UTC+08:00</span><input type="datetime-local" id="date-input" min="2000-01-01T08:00" max="2050-12-31T23:59" value="${twDate(state.time).slice(0,16)}" required></label><p class="muted" style="font-size:12px">日期範圍 2000–2050。暫停時間後，比較同一天體的位置變化。</p><div class="dialog-actions"><button type="button" data-action="shift-day" data-value="-1" class="secondary">前一天</button><button type="button" data-action="shift-day" data-value="1" class="secondary">後一天</button><button class="primary" type="submit">套用時間</button></div></form>`);$('#date-form').addEventListener('submit',e=>{e.preventDefault();const t=Date.parse($('#date-input').value+'+08:00');if(!Number.isFinite(t))return;state.playing=false;setTime(t);close();});}
function download(name,content,type='application/json'){const blob=content instanceof Blob?content:new Blob([content],{type});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);}
function persistNotes(){try{localStorage.setItem(storeKey,JSON.stringify(notes));storageAvailable=true;return true;}catch{storageAvailable=false;toast('瀏覽器無法儲存，請先匯出筆記備份。');return false;}}
function noteEditor(){const s=objects.get(state.selected);modal('記下這次的發現',`<form id="note-form"><p class="muted" style="font-size:12px">${esc(s.name)} · ${fmt(state.time)} · ${esc(state.place.name)}</p><label class="field" style="margin-top:18px"><span>觀察紀錄</span><textarea id="note-text" placeholder="我觀察到…" maxlength="4000" required></textarea></label><label class="field"><span>這筆紀錄將保存在此瀏覽器，可從「筆記」匯出備份。</span></label><div class="dialog-actions"><button type="button" data-action="close" class="secondary">取消</button><button type="submit" class="primary">儲存筆記</button></div></form>`);$('#note-text').focus();$('#note-form').addEventListener('submit',e=>{e.preventDefault();const text=$('#note-text').value.trim();if(!text)return;notes.unshift({id:crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`,text,object:s.name,objectId:s.id,created:new Date().toISOString(),scene:snapshot(),lesson:lessons[state.lesson].title});if(notes.length>500){notes.pop();toast('保留最近 500 筆筆記，請定期匯出。');}const saved=persistNotes();if(progress()===3)state.completed=4;close();renderLesson();toast(saved?'觀察已保存到我的筆記':'已暫存於本次頁面，請立即匯出備份');});}
function showNotes(){modal('我的觀測筆記',`<p>這個版本共有 ${notes.length} 筆紀錄。A／B／C 各自保存，可透過匯出匯入交換。${!storageAvailable?'目前瀏覽器儲存不可用，請立即匯出備份。':''}</p><div class="dialog-actions" style="margin:0 0 18px"><button class="secondary" data-action="export-notes">匯出備份</button><button class="secondary" data-action="import-notes">匯入筆記</button><button class="primary" data-action="save-note">新增紀錄</button></div><input id="import-file" type="file" accept="application/json,.json" hidden>${notes.length?notes.map(n=>`<article class="note-entry"><h3>${esc(n.object)} · ${esc(n.lesson)}</h3><small>${esc(n.scene?.time?fmt(Date.parse(n.scene.time)):n.created)} · ${esc(n.scene?.place?.name||'')}</small><p>${esc(n.text)}</p><button class="text-button" data-action="restore-note" data-id="${esc(n.id)}">回到觀測情境</button><button class="text-button danger" data-action="delete-note" data-id="${esc(n.id)}">刪除</button></article>`).join(''):`<div class="empty-state">${icon('note')}<p>你的星空故事，從第一筆觀察開始。<br>選取一顆星，寫下你看見的變化。</p></div>`}`);$('#import-file').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>3e6)throw Error('檔案不可超過 3 MB');const data=JSON.parse(await f.text());if(data.v!==1||!Array.isArray(data.notes)||data.notes.length>500)throw Error('筆記檔案格式不正確');const clean=data.notes.map(n=>{if(!n||typeof n.text!=='string'||n.text.length>4000||typeof n.object!=='string'||n.object.length>100||typeof n.lesson!=='string'||n.lesson.length>100)throw Error('有無法讀取的筆記內容');return {id:crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random()),text:n.text,object:n.object,objectId:objects.has(String(n.objectId))?String(n.objectId):'91262',created:new Date().toISOString(),lesson:n.lesson,scene:C.validScene(n.scene)};});if(notes.length+clean.length>500)throw Error('最多保存 500 筆；請先整理既有筆記');notes.push(...clean);const ok=persistNotes();showNotes();toast(ok?`已匯入 ${clean.length} 筆紀錄`:'已匯入至本次頁面，請立即匯出備份');}catch(err){toast(err.message||'匯入失敗');}});}
function share(){const scene=snapshot();if(scene.place.name==='我的位置'){scene.place={name:'概略位置',lat:Math.round(scene.place.lat),lon:Math.round(scene.place.lon)};}const hash='#scene='+C.encodeScene(scene);const url=location.href.split('#')[0]+hash;modal('分享同一片星空',`<p>分享目前的時間、位置、視角與圖層，讓同學開啟相同情境。分享內容不包含筆記或作答進度。</p><p class="muted">${fmt(Date.parse(scene.time))} · ${esc(scene.place.name)}（${scene.place.lat.toFixed(2)}°, ${scene.place.lon.toFixed(2)}°）</p><label class="field"><span>情境連結${location.protocol==='file:'?'（本機檔案連結僅適用同一電腦；跨裝置請先部署網站）':''}</span><textarea id="share-url" readonly>${esc(url)}</textarea></label><div class="dialog-actions"><button class="primary" data-action="copy-share">複製連結</button><button class="secondary" data-action="export-scene">下載情境檔案</button></div>`);}
function about(){modal('AstroEdu · 資料與版本',`<p>版本 0.3.5 · ${theme} 版。三款介面使用相同星圖、課程與操作邏輯。</p><div class="about-list"><p>星表：5,044 顆六等以內恆星，XHIP / d3-celestial。星座連線：d3-celestial；銀河輪廓：José R. Vieira / Milky Way Outline Catalog。</p><p>天文計算：Astronomy Engine。恆星採 J2000 星表並轉換至日期地平座標；此版未套用恆星自行、觀測折射與大氣消光。銀河亮度、星點尺寸為示意。</p><p>所有地點的時間顯示皆為 UTC+08:00；位置會影響天體方向。此版提供課堂探索，不作精密觀測排程依據。</p><p><a href="https://github.com/ofrohn/d3-celestial" target="_blank" rel="noopener">星圖資料來源</a> · <a href="https://github.com/cosinekitty/astronomy" target="_blank" rel="noopener">計算程式來源</a> · <a href="CREDITS.md" target="_blank">完整資料與授權說明</a></p></div>`);}
function help(){modal('開始探索夜空',`<div class="about-list"><p><b>拖曳與縮放</b><br>單指或滑鼠拖曳轉動星空；雙指或滑鼠滾輪縮放。鍵盤方向鍵移動，＋／－調整視野。</p><p><b>選取天體</b><br>點擊星點查看資訊，或按搜尋（快捷鍵 /）。「回到目標」會重新置中；目標卡準心可持續追蹤。</p><p><b>時間與地點</b><br>點擊日期編輯時間，拖曳滑桿比較一天內的星空。位置按鈕可選擇城市；時間一律顯示台灣時間。</p><p><b>課程與筆記</b><br>依序找到目標，預測後再做實驗。筆記會保存在目前版本的瀏覽器儲存空間，請定期匯出。</p><p><b>看不到天體？</b><br>檢查高度是否低於 0°。可切換觀測時間，或在圖層關閉地平遮罩作教學比較。</p><p><b>三版相同功能</b><br>A 是深色觀測站，B 是明亮教學工作台，C 是探索任務工作室。樣式不同，操作與教材相同。</p></div>`);}
async function action(name,el){switch(name){
 case 'search':search();break;case 'search-select':select(el.dataset.id);close();break;case 'select':select(el.dataset.id);break;
 case 'constellation':{const f=coordLines.find(f=>f.id===el.dataset.id);if(!f)break;const sum=f.paths.flat().reduce((a,v)=>a.map((x,i)=>x+v[i]),[0,0,0]),norm=Math.hypot(...sum),p=fromVector(rotate(sum.map(x=>x/norm)));state.camera={az:p.az,alt:C.clamp(p.alt,-89,89),fov:65};state.track=false;dirty=true;close();updateUI();toast(`已移至${cn[f.id]||f.id}星區`);break;}
 case 'locate-now':startDialog();break;case 'start-observing':beginObservation();break;case 'manual-explore':manualMode();close();break;case 'sensor-settings':advanced?.arPanel();break;case 'ar':if(!state.live){startDialog();toast('請先開始觀星，再開啟 AR 相機');}else try{await advanced.toggleCamera();updateUI();}catch(e){toast(e.message);}break;case 'advanced':advanced?.open();break;case 'courses':showCourses();break;case 'load-lesson':loadLesson(el.dataset.id);break;case 'close':close();break;
 case 'explore':$('#sky').focus();if(innerWidth<=850)$('.sky-card').scrollIntoView({block:'center',behavior:'smooth'});break;
 case 'layers':layers();break;case 'night':state.layers.night=!state.layers.night;updateUI();dirty=true;break;
 case 'zoom-in':state.camera.fov=C.clamp(state.camera.fov*.8,15,150);dirty=true;updateUI();break;case 'zoom-out':state.camera.fov=C.clamp(state.camera.fov/ .8,15,150);dirty=true;updateUI();break;
 case 'north':state.camera.az=0;state.camera.alt=C.clamp(state.place.lat,0,70);state.camera.fov=95;state.track=false;dirty=true;updateUI();break;
 case 'recenter':viewTarget();updateUI();break;case 'track':if(state.live){state.moonGuide=state.selected==='Moon';updateUI();break;}state.track=!state.track;if(state.track)viewTarget();updateUI();dirty=true;break;
 case 'play':manualMode();state.playing=!state.playing;updateUI();break;case 'previous':manualMode();state.playing=false;setTime(state.time-3600000);break;case 'next':manualMode();state.playing=false;setTime(state.time+3600000);break;
 case 'now':state.playing=false;setTime(Date.now());toast('已回到現在時間');break;case 'datetime':manualMode();dateDialog();break;case 'shift-day':manualMode();setTime(state.time+Number(el.dataset.value)*86400000);dateDialog();break;
 case 'location':locationDialog();break;case 'geolocate':{
 if(!navigator.geolocation){toast('此瀏覽器不支援定位，請手動輸入經緯度');break;}
 const request=++geoRequest,form=$('#location-form'),message=$('#geo-status');el.disabled=true;message.textContent='正在取得位置，最多等待 8 秒；請確認瀏覽器的位置權限。';
 let done=false;const finish=(text)=>{if(request!==geoRequest||!form.isConnected)return false;done=true;clearTimeout(timer);el.disabled=false;message.textContent=text;return true;};
 const timer=setTimeout(()=>{if(!done)finish('定位等待已超過 8 秒。可重試，或直接輸入經緯度；不會套用舊位置。');done=true;},8000);
 navigator.geolocation.getCurrentPosition(p=>{if(done)return;const c=p.coords;if(!Number.isFinite(c.latitude)||!Number.isFinite(c.longitude)||Math.abs(c.latitude)>90||Math.abs(c.longitude)>180){finish('裝置回傳的位置無效，請重試。');return;}
 const accuracy=Number.isFinite(c.accuracy)?`估計誤差約 ${Math.round(c.accuracy)} 公尺`:'装置未提供誤差';if(!finish(`已取得 ${c.latitude.toFixed(5)}, ${c.longitude.toFixed(5)}；${accuracy}。請確認後按「套用位置」。`))return;
 $('#lat').value=c.latitude.toFixed(6);$('#lon').value=c.longitude.toFixed(6);$('#place-name').value='我的位置';$('#place-select').value='custom';
 },e=>{if(!done)finish(e.code===1?'位置權限未允許，請在瀏覽器網站設定允許定位，或手動輸入。':e.code===3?'定位逾時，請重試或手動輸入經緯度。':'裝置無法取得位置；可移至空曠處重試，或手動輸入經緯度。');},{timeout:8000,maximumAge:0,enableHighAccuracy:true});break;}
 case 'hint':{const n=progress();$('#hint-text').textContent=lessons[state.lesson].hints[Math.min(3,n)];$('#hint-text').hidden=false;break;}
 case 'reset-lesson':loadLesson(state.lesson);toast('已回到課程初始情境');break;
 case 'predict':if(state.completed!==1)break;state.prediction=el.dataset.value;state.completed=2;renderLesson();toast('預測已記錄，接著用星空驗證。');break;
 case 'experiment':{if(state.completed!==2)break;manualMode();state.playing=false;state.track=false;const next=state.lesson==='seasons'?C.shiftMonth(state.time,3):state.time+(state.lesson==='moon'?7*86400000:7200000);setTime(next);state.experiment=true;state.completed=3;renderLesson();dirty=true;break;}
 case 'save-note':noteEditor();break;case 'notes':showNotes();break;
 case 'export-notes':download(`AstroEdu-${theme}-notes.json`,JSON.stringify({v:1,exportedAt:new Date().toISOString(),notes},null,2));break;
 case 'import-notes':$('#import-file').click();break;
 case 'restore-note':{const n=notes.find(n=>n.id===el.dataset.id);if(n){applyScene(n.scene);if(objects.has(n.objectId))state.selected=n.objectId;updateUI();close();toast('已還原觀測情境');}break;}
 case 'delete-note':{const n=notes.find(n=>n.id===el.dataset.id);if(n)modal('刪除這筆紀錄？',`<p>即將刪除「${esc(n.object)}」的觀測筆記。需要保留時，請先匯出备份。</p><div class="dialog-actions"><button class="secondary" data-action="notes">保留</button><button class="primary" data-action="confirm-delete" data-id="${esc(n.id)}">刪除紀錄</button></div>`);break;}
 case 'confirm-delete':notes=notes.filter(n=>n.id!==el.dataset.id);persistNotes();showNotes();break;
 case 'share':share();{const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.hidden=true;input.id='scene-file';$('#dialog-body').append(input);const button=document.createElement('button');button.className='secondary';button.dataset.action='import-scene';button.textContent='匯入情境檔案';$('#dialog-body .dialog-actions').append(button);input.addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>100000)throw Error('情境檔案不可超過 100 KB');const s=C.validScene(JSON.parse(await file.text()));applyScene(s);close();toast('已載入情境，課程進度重新開始');}catch(err){toast(err.message||'無法讀取情境檔案');}});}break;
 case 'import-scene':$('#scene-file').click();break;
 case 'copy-share':try{await navigator.clipboard.writeText($('#share-url').value);toast('情境連結已複製');}catch{$('#share-url').select();toast('請長按或按 Ctrl/Cmd+C 複製連結');}break;
 case 'export-scene':download('AstroEdu-scene.json',JSON.stringify(snapshot(),null,2));break;
 case 'capture':draw();canvas.toBlob(blob=>{if(blob)download(`AstroEdu-${theme}-${twDate(state.time).slice(0,10)}.png`,blob,'image/png');else toast('無法產生截圖，請再試一次。');},'image/png');break;
 case 'fullscreen':try{if(document.fullscreenElement)await document.exitFullscreen();else if($('.sky-card').requestFullscreen)await $('.sky-card').requestFullscreen();else toast('此裝置可使用瀏覽器加入主畫面，或旋轉為橫向觀星。');}catch{toast('無法進入全螢幕，請使用橫向畫面。');}break;
 case 'help':help();break;case 'about':about();break;
 }}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el){Promise.resolve(action(el.dataset.action,el)).catch(err=>{console.error(err);toast('操作未完成，請再試一次。');});}});
document.addEventListener('change',e=>{if(e.target.dataset.layer){state.layers[e.target.dataset.layer]=e.target.checked;dirty=true;updateUI();}});
$('#speed').addEventListener('change',e=>{state.rate=Number(e.target.value);updateUI();});
$('#time-range').addEventListener('input',e=>{manualMode();state.playing=false;const local=new Date(state.time+28800000);local.setUTCHours(0,0,0,0);setTime(local.getTime()-28800000+Number(e.target.value)*60000);});
$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog')){const r=$('#dialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close();}});
const pointers=new Map();let startPoint=null,pinch=null,dragged=false;
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});startPoint={x:e.clientX,y:e.clientY};dragged=false;state.track=false;if(pointers.size===2){const p=[...pointers.values()];pinch={distance:Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y),fov:state.camera.fov};}});
canvas.addEventListener('pointermove',e=>{const prev=pointers.get(e.pointerId);if(!prev)return;const dx=e.clientX-prev.x,dy=e.clientY-prev.y;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2&&pinch){const p=[...pointers.values()],d=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);state.camera.fov=C.clamp(pinch.fov*pinch.distance/Math.max(d,10),15,150);dragged=true;}else{if(startPoint&&Math.hypot(e.clientX-startPoint.x,e.clientY-startPoint.y)>5)dragged=true;state.camera.az=C.wrap(state.camera.az-dx*state.camera.fov/w);state.camera.alt=C.clamp(state.camera.alt+dy*state.camera.fov/w,-89,89);}dirty=true;});
canvas.addEventListener('pointerup',e=>{const multi=pointers.size>1;pointers.delete(e.pointerId);pinch=null;if(!dragged&&!multi){const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;const near=hits.map(p=>({...p,d:Math.hypot(p.x-x,p.y-y)})).filter(p=>p.d<24).sort((a,b)=>a.d-b.d);if(near.length)select(near[0].id,false);}if(!pointers.size)startPoint=null;updateUI();});
canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);pinch=null;startPoint=null;dragged=true;});
canvas.addEventListener('wheel',e=>{e.preventDefault();state.camera.fov=C.clamp(state.camera.fov*Math.exp(e.deltaY*.001),15,150);dirty=true;updateUI();},{passive:false});
document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||$('#dialog').open)return;if(e.key==='/'){e.preventDefault();search();}if(e.target===canvas){const step=state.camera.fov/25;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-',' '].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')state.camera.az=C.wrap(state.camera.az-step);if(e.key==='ArrowRight')state.camera.az=C.wrap(state.camera.az+step);if(e.key==='ArrowUp')state.camera.alt=C.clamp(state.camera.alt+step,-89,89);if(e.key==='ArrowDown')state.camera.alt=C.clamp(state.camera.alt-step,-89,89);if(e.key==='+'||e.key==='=')state.camera.fov=C.clamp(state.camera.fov*.9,15,150);if(e.key==='-')state.camera.fov=C.clamp(state.camera.fov/ .9,15,150);if(e.key===' ')state.playing=!state.playing;state.track=false;dirty=true;updateUI();}});
function frame(t){const dt=lastFrame?Math.min(t-lastFrame,2000):0;lastFrame=t;if(state.playing&&!document.hidden){state.time=C.clamp(state.time+dt*state.rate,Date.UTC(2000,0,1),Date.UTC(2050,11,31,15,59));if(state.time===Date.UTC(2000,0,1)||state.time===Date.UTC(2050,11,31,15,59))state.playing=false;dirty=true;}if(dirty&&t-lastRender>30){draw();lastRender=t;}if(t-lastUI>500){if(state.live){state.time=Date.now();dirty=true;}updateUI();if(advanced?.active())dirty=true;lastUI=t;}requestAnimationFrame(frame);}
function init(){if(!ctx||!A){$('#sky-loading').textContent='星圖未能載入，請確認檔案完整後重新開啟。';return;}focusTriangle();if(location.hash.startsWith('#scene=')){try{applyScene(C.decodeScene(location.hash.slice(7)));}catch(e){toast(e.message);}}renderLesson();resize();new ResizeObserver(resize).observe($('.sky-card'));$('#sky-loading').remove();requestAnimationFrame(frame);if(!location.hash.startsWith('#scene='))startDialog();if(theme==='C'){$('.course-nav').textContent='任務';$('.notes-nav').textContent='我的發現';}}
if(window.SkyAdvanced)advanced=window.SkyAdvanced({state,A,C,canvas,pos,objects,modal,close,toast,fmt,esc,setTime,select,snapshot,download,change:()=>{cacheTime=null;dirty=true;updateUI();},drawSky:draw});
init();
// Same state/actions are exposed only when the browser implements WebMCP.
if(document.modelContext?.registerTool){const lifecycle=new AbortController();for(const tool of [{name:'read_sky_scene',description:'Read current astronomy scene and selected object, without changing state.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({...snapshot(),selected:state.selected})},{name:'select_sky_object',description:'Select and centre a catalog object in the visible star chart.',inputSchema:{type:'object',properties:{objectId:{type:'string'}},required:['objectId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||typeof input.objectId!=='string'||!objects.has(input.objectId))throw Error('Unknown catalog object');select(input.objectId);draw();return {selected:state.selected,scene:snapshot()};}}]){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
})();
